name: Build & deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  create_env:
    name: Create Env File from Secrets
    runs-on: ubuntu-latest
    
    steps:
        # Checkout the branch
      - name: Checkout
        uses: actions/checkout@v3
        
        # Create the test environment file from Actions Secrets
        # You don't have to cat out your secrets file, but if you do it will just show as *** in the logs. It basically just confirms it actually exists.
      - name: Echo secrets
        run: |
          echo $TEST_ENV_FILE >> .env
          cat .env
        shell: bash
        env:
          # Feel free to rename this variable, but make sure to update it everywhere. You should paste your entire file in your secrets
          TEST_ENV_FILE : ${{secrets.ENV_SECRETS}}
          
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18.x
    
    - name: Install NPM packages
      run: npm ci
    
    - name: Build project
      run: npm run build
      env:
        REACT_APP_ABLY_SECRET_KEY: ${{ secrets.REACT_APP_ABLY_SECRET_KEY }}

    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: ./build
  
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: ./build

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
